name: documentation release

on: 
    release:
        types: [released]
    workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Setup just
        uses: extractions/setup-just@v2
      - name: Sphinx build
        run: just docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: built_docs/
          force_orphan: true